[project]
name = "uipathagent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "uipath>=2.6.30",
]
authors = [{ name = "Sugandha Bansal", email = "sugandhabansal31@gmail.com" }]